
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 22 10:07:34 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 22;
  public static final int OVER = 29;
  public static final int LCORC = 30;
  public static final int LPAREN = 32;
  public static final int SEMI = 34;
  public static final int REPEAT = 8;
  public static final int INT = 13;
  public static final int FOR = 5;
  public static final int MINUS = 27;
  public static final int WRITE = 11;
  public static final int RPAREN = 33;
  public static final int AND = 18;
  public static final int LT = 21;
  public static final int OR = 19;
  public static final int RT = 23;
  public static final int RETU = 36;
  public static final int BOOL = 12;
  public static final int RTE = 24;
  public static final int BEGIN = 6;
  public static final int UNTIL = 9;
  public static final int NUM = 16;
  public static final int PLUS = 26;
  public static final int ASSIGN = 17;
  public static final int IF = 2;
  public static final int RCORC = 31;
  public static final int ID = 15;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int DIF = 25;
  public static final int VOID = 14;
  public static final int EQ = 20;
  public static final int TIMES = 28;
  public static final int ELSE = 4;
  public static final int READ = 10;
  public static final int THEN = 3;
  public static final int END = 7;
}

